// import 'package:sufiyana_kaam/models/process-task.dart';
//
// class DummyData {
//   var data = [
//     ProcessTask(
//       id: "1",
//       title: "Create an App",
//       description: "Develop a Flutter application with clean UI.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 1,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "2",
//       title: "Test the App",
//       description: "Perform thorough testing on different devices for bugs.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 2,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "3",
//       title: "Prepare App Icon and Quality Screenshots",
//       description: "Design a high-quality app icon and take screenshots for the Play Store listing.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 3,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "4",
//       title: "Generate Signed APK/AAB",
//       description: "Build a release version of the app using a keystore.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 4,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "5",
//       title: "Create Play Console Account",
//       description: "Sign up or log in to Google Play Console and set up developer details.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 5,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "6",
//       title: "Create App Listing",
//       description: "Enter app details like title, description, category, and privacy policy.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 6,
//       priority: 'Normal',
//     ),
//
//     ProcessTask(
//       id: "7",
//       title: "Upload APK/AAB",
//       description: "Upload the signed APK or AAB to the Play Console.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 7,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "8",
//       title: "Set Pricing & Distribution",
//       description: "Choose countries for distribution and set whether the app is free or paid.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 8,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "9",
//       title: "Review and Submit for Review",
//       description: "Ensure everything is complete and submit the app for Google’s review.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 9,
//       priority: 'Normal',
//     ),
//     ProcessTask(
//       id: "10",
//       title: "Monitor App Status",
//       description: "Wait for approval and monitor the review process for any required changes.",
//       date: DateTime.now().toString(),
//       time: DateTime.now().toString(),
//       order: 10,
//       priority: 'Normal',
//     ),
//   ];
// }
